[package]
name = "rust_stuff"
version = "0.1.0"
authors = ["Joe Farebrother <joseph.farebrother@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.2.1", features = ["derive"] }


